# Jicofo HOCON configuration. See reference.conf in /usr/share/jicofo/jicofo.jar for
#available options, syntax, and default values.
jicofo {
  xmpp: {
    client: {
      client-proxy: "focus.jitsi-00.zitovoice.com"
      xmpp-domain: "jitsi-00.zitovoice.com"
      domain: "auth.jitsi-00.zitovoice.com"
      username: "focus"
      password: "bq6S4ix09M2PU8XX"
    }
    trusted-domains: [ "recorder.jitsi-00.zitovoice.com" ]
  }
  bridge: {
    brewery-jid: "JvbBrewery@internal.auth.jitsi-00.zitovoice.com"
  }
}
