videobridge {
    apis {
        rest {
            enabled = true
        }
    }
    http-servers {
        public {
            port = 9090
        }
    }
    websockets {
        enabled = true
        domain = "jitsi-00.zitovoice.com:443"
        tls = true
    }
}
